### ISSUE TITLE
TIFF IFD concatenations/removals output images that fail JHOVE validation check for value offset word-alignment

### ISSUE THREAD

**Issue by fiendish** [DigitalSlideArchive/tifftools#51]
(https://jhove.openpreservation.org/modules/tiff/)

```
> python -c 'import tifftools;tifftools.tiff_concat(["good1.svs", "good2.svs"], "out.svs", overwrite=True)'
> jhove -m TIFF-hul out.svs

Jhove (Rel. 1.24.1, 2020-03-16)
 Date: 2021-07-15 20:14:30 MDT
 RepresentationInformation: out.svs
  ReportingModule: TIFF-hul, Rel. 1.9.2 (2019-12-10)
  LastModified: 2021-07-15 20:14:20 MDT
  Size: 875685820
  Format: TIFF
  Status: Not well-formed
  SignatureMatches:
   TIFF-hul
  ErrorMessage: Value offset not word-aligned: 8842289
   ID: TIFF-HUL-4
   Offset: 8858224
  MIMEtype: image/tiff
```

https://web.archive.org/web/20160324105748/https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf on page 15 (about IFD entries) says:

> Bytes 8-11 The Value Offset, the file offset (in bytes) of the Value for the field. The Value is expected to begin on a word boundary; the correspond- ing Value Offset will thus be an even number. This file offset may point anywhere in the file, even after the image data.

**Comment by manthey** [comment]
@fiendish Thank you for reporting this.

**Comment by fiendish** [comment]
I'm still getting the error after the change.

**Comment by manthey** [comment]
@fiendish Try again.

**Comment by fiendish** [comment]
Looks great. Thanks!
